/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ag_game_card */

#ifndef _Included_com_ag_game_card
#define _Included_com_ag_game_card
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ag_game_card_COUNTER_PULSE_DURATION
#define com_ag_game_card_COUNTER_PULSE_DURATION 20L
#undef com_ag_game_card_OUTPUT_BIT_BUTTON_MINUS
#define com_ag_game_card_OUTPUT_BIT_BUTTON_MINUS 25L
#undef com_ag_game_card_OUTPUT_BIT_BUTTON_PLUS
#define com_ag_game_card_OUTPUT_BIT_BUTTON_PLUS 23L
#undef com_ag_game_card_OUTPUT_BIT_BUTTON_AUTOSTART
#define com_ag_game_card_OUTPUT_BIT_BUTTON_AUTOSTART 22L
#undef com_ag_game_card_OUTPUT_BIT_BUTTON_START
#define com_ag_game_card_OUTPUT_BIT_BUTTON_START 24L
#undef com_ag_game_card_OUTPUT_BIT_BUTTON_BACK
#define com_ag_game_card_OUTPUT_BIT_BUTTON_BACK 20L
#undef com_ag_game_card_OUTPUT_BIT_BUTTON_MAXBET
#define com_ag_game_card_OUTPUT_BIT_BUTTON_MAXBET 16L
#undef com_ag_game_card_OUTPUT_BIT_COUNTER0
#define com_ag_game_card_OUTPUT_BIT_COUNTER0 0L
#undef com_ag_game_card_OUTPUT_BIT_COUNTER1
#define com_ag_game_card_OUTPUT_BIT_COUNTER1 1L
#undef com_ag_game_card_OUTPUT_BIT_COUNTER2
#define com_ag_game_card_OUTPUT_BIT_COUNTER2 2L
#undef com_ag_game_card_OUTPUT_BUTTON_MINUS
#define com_ag_game_card_OUTPUT_BUTTON_MINUS 33554432L
#undef com_ag_game_card_OUTPUT_BUTTON_PLUS
#define com_ag_game_card_OUTPUT_BUTTON_PLUS 8388608L
#undef com_ag_game_card_OUTPUT_BUTTON_AUTOSTART
#define com_ag_game_card_OUTPUT_BUTTON_AUTOSTART 4194304L
#undef com_ag_game_card_OUTPUT_BUTTON_START
#define com_ag_game_card_OUTPUT_BUTTON_START 16777216L
#undef com_ag_game_card_OUTPUT_BUTTON_BACK
#define com_ag_game_card_OUTPUT_BUTTON_BACK 1048576L
#undef com_ag_game_card_OUTPUT_BUTTON_MAXBET
#define com_ag_game_card_OUTPUT_BUTTON_MAXBET 65536L
/*
 * Class:     com_ag_game_card
 * Method:    Initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ag_game_card_Initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    GetAcceptorAddressBill
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ag_game_card_GetAcceptorAddressBill
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    GetAcceptorAddressCoin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ag_game_card_GetAcceptorAddressCoin
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    EnableAcceptorBill
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ag_game_card_EnableAcceptorBill
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    EnableAcceptorCoin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ag_game_card_EnableAcceptorCoin
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    DisableAcceptorBill
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ag_game_card_DisableAcceptorBill
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    DisableAcceptorCoin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ag_game_card_DisableAcceptorCoin
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    GetButtons
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_ag_game_card_GetButtons
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    getLastCoin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ag_game_card_getLastCoin
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    getLastBill
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_ag_game_card_getLastBill
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ag_game_card_close
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    controlBrightness
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_ag_game_card_controlBrightness
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_ag_game_card
 * Method:    pulseStart
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ag_game_card_pulseStart
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ag_game_card
 * Method:    pulseRemaining
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ag_game_card_pulseRemaining
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    sendCounterOnePulse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ag_game_card_sendCounterOnePulse
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    sendCounterTwoPulse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ag_game_card_sendCounterTwoPulse
  (JNIEnv *, jobject);

/*
 * Class:     com_ag_game_card
 * Method:    sendCounterThreePulse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ag_game_card_sendCounterThreePulse
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
